# .github/workflows/publish-to-pypi.yml
name: Publish Python package to PyPI

on:
  release:
    types: [published] # This workflow runs when a new GitHub Release is published
  workflow_dispatch: # Allows manual trigger of the workflow from GitHub UI

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4 # Checks out your repository

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Use a recent Python 3 version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Build package
      run: python setup.py sdist bdist_wheel # Builds the source and wheel distributions

    - name: Publish package to PyPI
      env:
        TWINE_USERNAME: __token__ # Required for token-based authentication
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }} # PyPI API token stored as a secret
      run: twine upload dist/* # Uploads the built package to PyPI

